services:
  backend:
    build: .
    container_name: ${PROJECT_NAME}_backend
    restart: always
    ports:
      - "8003:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./app:/app/app
    command: [ "poetry", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--log-level", "debug" ]
    networks:
      - startups

  db:
    image: postgres:17
    container_name: ${PROJECT_NAME}_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      - startups
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  startups:


volumes:
  database:
